#!/usr/bin/env python3
"""PF-based text generator for Atari 2600 HUD.

Converts text to pre-computed playfield register patterns (PF0/PF1/PF2).
Each character is 3 pixels wide, 5 scanlines tall, spaced 4 PF-bits apart.
Fits 4 characters in the 20-bit playfield width.

PF register layout (left half, with reflection):
  PF0 bits 7-4: pixels 0-3  (border, set to $F0)
  PF1 bits 7-0: pixels 4-11 (2 characters, direct bit order)
  PF2 bits 0-7: pixels 12-19 (2 characters, REVERSED bit order!)

Usage:
    python3 tools/pf_text.py "TEST" output.asm
    python3 tools/pf_text.py --lines "LINE1;LINE2;LINE3" output.asm
"""

import sys
from pathlib import Path

FONT = {
    ' ': [0b000, 0b000, 0b000, 0b000, 0b000],
    'A': [0b010, 0b101, 0b111, 0b101, 0b101],
    'B': [0b110, 0b101, 0b110, 0b101, 0b110],
    'C': [0b011, 0b100, 0b100, 0b100, 0b011],
    'D': [0b110, 0b101, 0b101, 0b101, 0b110],
    'E': [0b111, 0b100, 0b110, 0b100, 0b111],
    'F': [0b111, 0b100, 0b110, 0b100, 0b100],
    'G': [0b011, 0b100, 0b101, 0b101, 0b011],
    'H': [0b101, 0b101, 0b111, 0b101, 0b101],
    'I': [0b111, 0b010, 0b010, 0b010, 0b111],
    'J': [0b001, 0b001, 0b001, 0b101, 0b010],
    'K': [0b101, 0b101, 0b110, 0b101, 0b101],
    'L': [0b100, 0b100, 0b100, 0b100, 0b111],
    'M': [0b101, 0b111, 0b101, 0b101, 0b101],
    'N': [0b101, 0b101, 0b101, 0b101, 0b011],
    'O': [0b010, 0b101, 0b101, 0b101, 0b010],
    'P': [0b110, 0b101, 0b110, 0b100, 0b100],
    'Q': [0b010, 0b101, 0b101, 0b110, 0b011],
    'R': [0b110, 0b101, 0b110, 0b101, 0b101],
    'S': [0b011, 0b100, 0b010, 0b001, 0b110],
    'T': [0b111, 0b010, 0b010, 0b010, 0b010],
    'U': [0b101, 0b101, 0b101, 0b101, 0b010],
    'V': [0b101, 0b101, 0b101, 0b010, 0b010],
    'W': [0b101, 0b101, 0b101, 0b111, 0b101],
    'X': [0b101, 0b101, 0b010, 0b101, 0b101],
    'Y': [0b101, 0b101, 0b010, 0b010, 0b010],
    'Z': [0b111, 0b001, 0b010, 0b100, 0b111],
    '0': [0b111, 0b101, 0b101, 0b101, 0b111],
    '1': [0b010, 0b110, 0b010, 0b010, 0b111],
    '2': [0b111, 0b001, 0b111, 0b100, 0b111],
    '3': [0b111, 0b001, 0b111, 0b001, 0b111],
    '4': [0b101, 0b101, 0b111, 0b001, 0b001],
    '5': [0b111, 0b100, 0b111, 0b001, 0b111],
    '6': [0b111, 0b100, 0b111, 0b101, 0b111],
    '7': [0b111, 0b001, 0b001, 0b001, 0b001],
    '8': [0b111, 0b101, 0b111, 0b101, 0b111],
    '9': [0b111, 0b101, 0b111, 0b001, 0b111],
    '.': [0b000, 0b000, 0b000, 0b000, 0b010],
    ':': [0b000, 0b010, 0b000, 0b010, 0b000],
    '-': [0b000, 0b000, 0b111, 0b000, 0b000],
}

PF1_CHARS = 2
PF2_CHARS = 2
TOTAL_CHARS = PF1_CHARS + PF2_CHARS


def _encode_pf1(patterns):
    """Encode 2 chars into PF1 (direct bit order).

    Char 0: bits 7-5, Char 1: bits 3-1. Bits 4,0 = 0 (gaps).
    Bit 7 = leftmost pixel.
    """
    val = 0
    # Char 0 at bits 7,6,5
    p = patterns[0]
    if p & 4: val |= 0x80  # bit 7
    if p & 2: val |= 0x40  # bit 6
    if p & 1: val |= 0x20  # bit 5
    # Char 1 at bits 3,2,1
    p = patterns[1]
    if p & 4: val |= 0x08  # bit 3
    if p & 2: val |= 0x04  # bit 2
    if p & 1: val |= 0x02  # bit 1
    return val


def _encode_pf2(patterns):
    """Encode 2 chars into PF2 (REVERSED bit order).

    PF2: bit 0 = leftmost pixel, bit 7 = rightmost pixel.
    Char 2: bits 0,1,2. Char 3: bits 4,5,6. Bits 3,7 = 0 (gaps).
    """
    val = 0
    # Char 2 at bits 0,1,2
    p = patterns[0]
    if p & 4: val |= 0x01  # bit 0 (MSB of char = leftmost = PF2 bit 0)
    if p & 2: val |= 0x02  # bit 1
    if p & 1: val |= 0x04  # bit 2
    # Char 3 at bits 4,5,6
    p = patterns[1]
    if p & 4: val |= 0x10  # bit 4
    if p & 2: val |= 0x20  # bit 5
    if p & 1: val |= 0x40  # bit 6
    return val


def encode_line(text):
    """Encode text to list of 5 (PF0, PF1, PF2) tuples."""
    text = text.upper()[:TOTAL_CHARS].ljust(TOTAL_CHARS)
    rows = []
    for row in range(5):
        pf1_pats = [FONT.get(ch, FONT[' '])[row] for ch in text[:PF1_CHARS]]
        pf2_pats = [FONT.get(ch, FONT[' '])[row] for ch in text[PF1_CHARS:]]
        rows.append((0xF0, _encode_pf1(pf1_pats), _encode_pf2(pf2_pats)))
    return rows


def main():
    if len(sys.argv) < 3:
        print("Usage: pf_text.py <text> <output.asm>", file=sys.stderr)
        print("       pf_text.py --lines 'L1;L2;L3' <output.asm>", file=sys.stderr)
        return 1

    if sys.argv[1] == "--lines":
        texts = [t.strip() for t in sys.argv[2].split(";")]
        output = Path(sys.argv[3])
    else:
        texts = [sys.argv[1]]
        output = Path(sys.argv[2])

    header = [
        "; Generated by tools/pf_text.py — PF-based HUD text data",
        "; PF0=border, PF1=chars 0-1 (direct), PF2=chars 2-3 (reversed)",
        "",
    ]
    body = []
    total = 0
    for text in texts:
        label = text.upper().replace(" ", "_").replace(".", "DOT")
        label = f"PF_{label}"
        rows = encode_line(text)
        body.append(f"; '{text}'")
        body.append(f"{label}:")
        for pf0, pf1, pf2 in rows:
            body.append(f"    .byte ${pf0:02X}, ${pf1:02X}, ${pf2:02X}")
            total += 3
        body.append("")

    output.write_text("\n".join(header + body) + "\n")
    print(f"pf_text: {len(texts)} lines, {total} bytes -> {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
