#!/usr/bin/env python3
"""Copyright micro-font packer — intro screen bottom-right line.

Text: "(c) Iuri Fiedoruk 2026" reference (screenshots/intro_screen_mess_fixed.png)
renders "© 2026 IURI FIEDORUK" bottom-right. Reference = visual reference only
(user 2026-10-07: no same-scale constraint).

Engine: the proven 48px sprite technique (TitleKernel .TkLoop clone in bank2
CopyrightBand): NUSIZ3 P0/P1 interleave = 6 glyph windows x 8px = 48px
content. Per-scanline budget (76c) hard-caps a line at 6 windows — mid-line
RESP re-stroke does not help (window count, not span, is the bottleneck).

Packs the string left-to-right into a 48px canvas, slices into 6 x 8px
slots, emits generated/copyright_font.asm in TitleFont convention:
byte0 = blank, byte7 = top row, byte1 = bottom row (loop draws Y=7 first).

Run: /home/iuri/python3/bin/python3 tools/copyright_font.py
"""
from pathlib import Path

SRC = Path(__file__).resolve().parent.parent
OUT = SRC / "generated" / "copyright_font.asm"

TEXT = "©2026"

# 5x7 glyphs sized to fit the 48px title strip while staying bold enough to be
# visible on a black title background. The earlier 3x5 variant was too thin and
# the generated rows were effectively blank in the lower pass.
GLYPHS = {
    " ": ["00000", "00000", "00000", "00000", "00000", "00000", "00000"],
    "©": ["01110", "10001", "10001", "10001", "10001", "10001", "01110"],
    "0": ["01110", "10001", "10001", "10001", "10001", "10001", "01110"],
    "2": ["01110", "10001", "00001", "00010", "00100", "01000", "11111"],
    "6": ["01110", "10000", "10000", "11110", "10001", "10001", "01110"],
    "I": ["11111", "00100", "00100", "00100", "00100", "00100", "11111"],
    "U": ["10001", "10001", "10001", "10001", "10001", "01010", "00100"],
    "R": ["11110", "10001", "10001", "11110", "10100", "10010", "10001"],
}

CANVAS_W = 48          # 6 windows x 8px (NUSIZ3 interleave)
ROWS = 7               # byte7 top .. byte1 bottom (byte0 blank)


def build_canvas():
    cols = []
    for ch in TEXT:
        if ch not in GLYPHS:
            raise SystemExit(f"missing glyph: {ch!r}")
        glyph = GLYPHS[ch]
        if len(glyph) != ROWS:
            raise SystemExit(f"{ch!r}: {len(glyph)} rows, need {ROWS}")
        w = len(glyph[0])
        if any(len(r) != w for r in glyph):
            raise SystemExit(f"{ch!r}: ragged rows")
        cols.append((ch, w, glyph))
    total = sum(w for _, w, _ in cols)
    if total > CANVAS_W:
        raise SystemExit(f"width {total} > {CANVAS_W}px canvas")
    # canvas[row][x] as list of lists
    canvas = [["."] * CANVAS_W for _ in range(ROWS)]
    x = 0
    layout = []
    for ch, w, glyph in cols:
        layout.append((ch, x, w))
        for r in range(ROWS):
            for i, bit in enumerate(glyph[r]):
                canvas[r][x + i] = "#" if bit == "1" else "."
        x += w
    return canvas, total, layout


def slots_bytes(canvas):
    """Slice 48px canvas into 6 x 8px slots; emit 8 bytes per slot."""
    out = []
    for slot in range(6):
        base = slot * 8
        rowbytes = []
        # byte7 = top row (r=0) ... byte1 = bottom (r=6), byte0 = blank
        rowbytes.append(0)
        for r in range(ROWS - 1, -1, -1):     # emit bottom..top -> b1..b7
            b = 0
            for i in range(8):
                x = base + i
                if x < CANVAS_W and canvas[r][x] == "#":
                    b |= 0x80 >> i
            rowbytes.append(b)
        out.append(rowbytes)                  # [b0, b1, ..., b7]
    return out


def preview(canvas, layout, total):
    print(f"TEXT: {TEXT}")
    print(f"ink: {total}px / {CANVAS_W}px canvas  (advance = glyph width, "
          f"word space = 1px built into ' ' glyph)")
    print("layout: " + " ".join(f"{ch}@{x}" for ch, x, w in layout))
    for r in range(ROWS):
        print("   " + "".join(canvas[r]))


def main():
    canvas, total, layout = build_canvas()
    preview(canvas, layout, total)
    slots = slots_bytes(canvas)

    lines = [
        "; generated by tools/copyright_font.py — DO NOT EDIT",
        f'; \"© 2026 IURI FIEDORUK\" packed {total}px into 48px canvas =',
        "; 6 x 8px slots (NUSIZ3 P0/P1 interleave, bank2 CopyrightBand .CbLoop).",
        "; TitleFont convention: byte0 blank, byte7 top, byte1 bottom.",
        "CopyrightFont:",
    ]
    for i, rowbytes in enumerate(slots):
        parts = ", ".join(f"%{b:08b}" for b in rowbytes)
        lines.append(f"    ; slot {i+1} (x {i*8}-{i*8+7})")
        lines.append(f"    .byte {parts}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(SRC)}")


if __name__ == "__main__":
    main()
